### ISSUE TITLE
mbslave sync >>/var/log/mbslave.log

### ISSUE THREAD

**Issue by jpbaboo** [acoustid/mbdata#10]
Hi First of all.. thks for your great job on MusicBrainz Server
Everything works find except mbslave sync  in crontab..
But mbslave sync >>/var/log/mbslave.log works find in command line mode
I'm under Ubuntu 19.10
Ths for any advice

**Comment by heyoni** [comment]
I know it's been a while but check our `MAILTO` var and see if that's set. Might be because your cron output is being mailed to you.
