### ISSUE TITLE
README references non-existent SQL files

### ISSUE THREAD

**Issue by autarch** [acoustid/mbdata#30]
I think the README is out of date with the actual SQL files. For example, it shows `mbslave psql -f CreateCollations.sql`, but that file doesn't exist.

I haven't checked every such command, but I think a number of them are no longer correct.

**Comment by Phrogz** [comment]
I'm experienced this same problem trying to install on macOS. 

```
phrogz@GrayBook MusicExplorer % mbslave psql -f CreateCollations.sql
Traceback (most recent call last):
  File "/usr/local/bin/mbslave", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/mbdata/replication.py", line 592, in main
    args.func(config, args)
  File "/usr/local/lib/python3.9/site-packages/mbdata/replication.py", line 529, in mbslave_psql_main
    with open(locate_sql_file(args.sql_file), 'rb') as input_sql_file:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.9/site-packages/mbdata/sql/CreateCollations.sql'
```

Sure enough, that file is not there:

```
phrogz@GrayBook MusicExplorer % ll /usr/local/lib/python3.9/site-packages/mbdata/sql/ | grep Collate
-rw-r--r--    1 phrogz  admin     886 Nov 12 20:00 CreateCollateIndexes.sql
-rw-r--r--    1 phrogz  admin     434 Nov 12 20:00 DropCollateIndexes.sql
```

Weird thing is that I did `pip install -U mbdata` for the first time tonight, and this file definitely DOES exist in the repo:

https://github.com/lalinsky/mbdata/blob/main/mbdata/sql/CreateCollations.sql

**Comment by autarch** [comment]
Hmm, maybe the package is out of date with the repo then? Yep, that's definitely the case - https://pypi.org/project/mbdata/ - the last release to PyPI was in May of 2019. I guess this just needs to be used by cloning the repo nowadays? But in the case the `README.md` still needs to be fixed to not recommend installing with `pip`.
