### ISSUE TITLE
CreateIndexes.sql -> "musicbrainz.ll_to_earth(double precision, double precision) does not exist"

### ISSUE THREAD

**Issue by Phrogz** [acoustid/mbdata#32]
Running `mbslave psql -f CreateIndexes.sql` executes for a long time with lots of "CREATE INDEX" outputs, but ultimately errors out with:

```
ERROR:  function musicbrainz.ll_to_earth(double precision, double precision) does not exist
LINE 1: CREATE INDEX place_idx_geo ON place USING gist (musicbrainz....
                                                        ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

**Comment by Phrogz** [comment]
The problem appears to be [this line](https://github.com/lalinsky/mbdata/blob/main/mbdata/sql/CreateIndexes.sql#L458):

```sql
CREATE INDEX place_idx_geo ON place USING gist (musicbrainz.ll_to_earth(coordinates[0], coordinates[1])) WHERE coordinates IS NOT NULL;
```

**Comment by Phrogz** [comment]
Commenting out that index, there's a further problem on line 629:

```sql
CREATE INDEX artist_idx_lower_unaccent_name_comment ON artist (lower(musicbrainz_unaccent(name)), lower(musicbrainz_unaccent(comment)));
```

produces error:

```
psql:/var/folders/gr/391stds133bg1326wp7w70tm0000gn/T/tmp0jh6fwzp.sql:629: ERROR:  function musicbrainz_unaccent(character varying) does not exist
LINE 1: ..._idx_lower_unaccent_name_comment ON artist (lower(musicbrain...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

**Comment by Phrogz** [comment]
Problem occurs on Postgres v13.4

**Comment by echoxxzz** [comment]
If I edit the lines in the CreateIndexes.sql script and remove the schema qualifier (ie. "musicbrainz.") it gets past those errors about the unknown function and creates the indexes.

I think the unaccent errors are because Musicbrainz dropped their musicbrainz-collate and musicbrainz-unaccent extensions, instead using PG’s builtin collation support for the former and replacing the latter with the unaccent extension from postgresql-contrib. 

https://blog.metabrainz.org/2020/05/04/reminder-upgrading-to-postgresql-12-on-may-18-2020/

I tried adding the PG unaccent extension:

psql musicbrainz -c 'CREATE EXTENSION earthdistance;'

but when I try and use the PG unaccent() function I get this error:
 
"functions in index expression must be marked IMMUTABLE".

**Comment by echoxxzz** [comment]
1.   Complete the first 3 steps to install mbdata and setup your mbslave.conf file.

      The SQL scripts in the mbdata repo haven't been updated in over 6 months so you need to 
      either clone the Musicbrainz git repo or download the latest Musicbrainz zip file from
      Github and copy and/or exact the contents of the musicbrainz-server-master/admin/sql folder
      and replace the files in the mbdata/sql folder.

      If you used pipx the mbdata/sql folder will be located somewhere like the following:

      ~/.local/pipx/venvs/mbdata/lib/python3.x/site-packages/mbdata/sql

      If needed, use find to locate your specific folder location.

      The remainder of the steps where taken verbatim from the Musicbrainz InitDb.pl script. This will create a complete
      Musicbrainz slave database will all tables, indexes, etc. You may want to customize as needed if say for instance
      you're not importing wikidocs or other non-essential data dumps.

2.   Create the Database:	

      sudo su - postgres
      createuser musicbrainz
      createdb -l C -E UNICODE -T template0 -O musicbrainz musicbrainz

      #MB now use DateTime->now to populate 'TIMESTAMP WITH TIME ZONE' columns in their code. 
      #DateTime->now outputs 'floating' UTC by default, but doesn't encode any timezone info in its output, so the
      #database must have its timezone set to UTC in order to correctly interpret those values.

      psql musicbrainz -c 'ALTER DATABASE musicbrainz SET timezone TO 'UTC';'

      psql musicbrainz -c 'CREATE EXTENSION IF NOT EXISTS cube WITH SCHEMA public;'
      psql musicbrainz -c 'CREATE EXTENSION IF NOT EXISTS earthdistance WITH SCHEMA public;'
      psql musicbrainz -c 'CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA public;'

      #exit out of sudo back to the account you setup for mbdata

3.   Prepare empty schemas:

      echo 'CREATE SCHEMA musicbrainz;' | mbslave psql -S
      echo 'CREATE SCHEMA statistics;' | mbslave psql -S
      echo 'CREATE SCHEMA cover_art_archive;' | mbslave psql -S
      echo 'CREATE SCHEMA wikidocs;' | mbslave psql -S
      echo 'CREATE SCHEMA documentation;' | mbslave psql -S
      echo 'CREATE SCHEMA event_art_archive;' | mbslave psql -S
      echo 'CREATE SCHEMA json_dump;' | mbslave psql -S
      echo 'CREATE SCHEMA report;' | mbslave psql -S
      echo 'CREATE SCHEMA sitemaps;' | mbslave psql -S

4.   Create tables structures:

      #The first script will give an error that the extensions already exist because we already added them in step 1. The
      #extensions have to be created in step 1 as you need to be a superuser account to create extensions. We just need
      #to run the Extensions.sql script to add the musicbrainz.ll_to_earth() function so index creation won't fail as reported
      #in this issue ticket.
	
      mbslave psql -f Extensions.sql	
      mbslave psql -f CreateCollations.sql
      mbslave psql -f CreateTables.sql
      mbslave psql -f caa/CreateTables.sql
      mbslave psql -f eaa/CreateTables.sql
      mbslave psql -f documentation/CreateTables.sql
      mbslave psql -f json_dump/CreateTables.sql
      mbslave psql -f report/CreateTables.sql
      mbslave psql -f sitemaps/CreateTables.sql
      mbslave psql -f statistics/CreateTables.sql
      mbslave psql -f wikidocs/CreateTables.sql

5.   Import the data dumps. Minimally you need the following two dump files:

      mbslave import mbdump.tar.bz2 mbdump-derived.tar.bz2
	
6.   Create the primary keys:

      mbslave psql -f CreatePrimaryKeys.sql
      mbslave psql -f caa/CreatePrimaryKeys.sql
      mbslave psql -f documentation/CreatePrimaryKeys.sql
      mbslave psql -f eaa/CreatePrimaryKeys.sql
      mbslave psql -f statistics/CreatePrimaryKeys.sql
      mbslave psql -f wikidocs/CreatePrimaryKeys.sql

7.   Create functions

      mbslave psql -f CreateSearchConfiguration.sql
      mbslave psql -f CreateFunctions.sql
      mbslave psql -f caa/CreateFunctions.sql
      mbslave psql -f eaa/CreateFunctions.sql
      mbslave psql -f CreateSlaveOnlyFunctions.sql

8.   Create indexes

      mbslave psql -f CreateIndexes.sql
      mbslave psql -f caa/CreateIndexes.sql
      mbslave psql -f eaa/CreateIndexes.sql
      mbslave psql -f json_dump/CreateIndexes.sql
      mbslave psql -f sitemaps/CreateIndexes.sql
      mbslave psql -f statistics/CreateIndexes.sql
      mbslave psql -f CreateSlaveIndexes.sql

9.   Set initial sequence values

      mbslave psql -f SetSequences.sql
      mbslave psql -f statistics/SetSequences.sql

10.  Create views and triggers and search indexes

      mbslave psql -f CreateViews.sql
      mbslave psql -f caa/CreateViews.sql
      mbslave psql -f eaa/CreateViews.sql
      mbslave psql -f CreateSlaveOnlyTriggers.sql
      mbslave psql -f CreateSearchIndexes.sql

**Comment by jeleffto** [comment]
Also having the same issue.  Are there any solutions?  If we skip creating the indices per above will that create integrity problems down the line?

**Comment by jeleffto** [comment]
If we add and run the Extensions.sql script from https://github.com/metabrainz/musicbrainz-server/blob/master/admin/sql/Extensions.sql, that should fix it, no?
