### ISSUE TITLE
CreateFunctions.sql -> function array_append(anyarray, anyelement) does not exist

### ISSUE THREAD

**Issue by Phrogz** [acoustid/mbdata#33]
```
phrogz@GrayBook MusicExplorer % mbslave psql -f CreateFunctions.sql
BEGIN
CREATE FUNCTION
psql:/var/folders/gr/391stds133bg1326wp7w70tm0000gn/T/tmps2a60q5n.sql:23: ERROR:  function array_append(anyarray, anyelement) does not exist

phrogz@GrayBook MusicExplorer % psql --version
psql (PostgreSQL) 14.1
```

**Comment by Phrogz** [comment]
Seems like perhaps the problem is PostgreSQL v14; going to try uninstalling, installing psql 13 and starting over.

**Comment by Phrogz** [comment]
Under psql 13.4 I get different error:

```
psql:/var/folders/gr/391stds133bg1326wp7w70tm0000gn/T/tmp9q3v99t1.sql:1729: ERROR:  text search configuration "musicbrainz.mb_simple" does not exist
LINE 6:   SELECT to_tsvector('musicbrainz.mb_simple', musicbrainz.mb...
```

**Comment by yvanzo** [comment]
I don’t know if this is the cause of the problem but I would recommend using PostgreSQL v12 instead (based on the section “[Schema Upgrade](https://github.com/lalinsky/mbdata#schema-upgrade)”).

**Comment by amCap1712** [comment]
https://github.com/metabrainz/musicbrainz-server/commit/38861c768d427970e9088cefc76604b05ee11bab made the MB SQL files compatible with PG 14 so trying with latest master which contains these changes should work now.
