### ISSUE TITLE
"musicbrainz.alternative_release_type" does not exist

### ISSUE THREAD

**Issue by agawronski** [acoustid/mbdata#35]
~/ftp.musicbrainz.org/pub/musicbrainz/data/fullexport/20211120-001843$ mbslave import mbdump.tar.bz2 mbdump-derived.tar.bz2
Importing data from mbdump.tar.bz2
 - Loading alternative_release_type to musicbrainz.alternative_release_type
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/mbslave", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/mbdata/replication.py", line 592, in main
    args.func(config, args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/mbdata/replication.py", line 253, in mbslave_import_main
    load_tar(filename, db, config, config.schemas.ignored_schemas, config.tables.ignored_tables)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/mbdata/replication.py", line 245, in load_tar
    cursor.copy_from(tar.extractfile(member), fulltable)
psycopg2.errors.UndefinedTable: relation "musicbrainz.alternative_release_type" does not exist

Seems to be related to the issue mentioned here:
https://community.metabrainz.org/t/database-replication-issue-with-mbdata-25-0-4/548110

**Comment by echoxxzz** [comment]
Same problem here any ideas why the copy_from method is failing using the fulltable name?

**Comment by echoxxzz** [comment]
https://github.com/psycopg/psycopg2/issues/1294

Looks like there was a change to the psycopg2 module and you cannot pass the schema into the copy_from method anymore.
The suggestion is to use the copy_expert() method instead.

**Comment by lincoln017** [comment]
I downgraded my psycopg2 module from 2.9.3 to 2.8.5 and everything worked fine -- no other changes necessary,.

**Comment by BriantOliveira** [comment]
I downloaded psycopg2 2.8.5, and I'm still getting this issue :/

**Comment by ozturkberkay** [comment]
Using `copy_expert` worked: `cursor.copy_expert(f"COPY {fulltable} FROM STDIN", tar.extractfile(member))`.
Beweare of [this error](https://github.com/acoustid/mbdata/issues/49) though...
