### ISSUE TITLE
mbslave command not found

### ISSUE THREAD

**Issue by lciaran** [acoustid/mbdata#44]
Hello,

I'm trying to import the MusicBrainz database. I'm a student and don't really know what I'm doing. I try to do the commands with the mbslave command, but it tells me that it doesn't exist (this inside the PostgreSQL, which I think is correct)
This is my mbslave file:

[database]
host=127.0.0.1
port=5432
name=musicbrainz
user=musicbrainz
password=musicbrainz

[musicbrainz]
base_url=https://metabrainz.org/api/musicbrainz/
token=MyToken

[tables]
ignore=
#ignore=tracklist_index

[schemas]
musicbrainz=musicbrainz
statistics=statistics
cover_art_archive=cover_art_archive
event_art_archive=event_art_archive
wikidocs=wikidocs
documentation=documentation
ignore=
#ignore=statistics,cover_art_archive,wikidocs,documentation

Can someone help me? I'm not sure what I'm doing wrong.

**Comment by echoxxzz** [comment]
Are you trying to run mbslave inside psql? 
Run it from the shell and use my updated instructions from issue #43 otherwise it will fail.
