### ISSUE TITLE
New release (28)

### ISSUE THREAD

**Issue by bt0r** [acoustid/mbdata#66]
Hi guys,

Our mbslave is stuck since few days, it seems to be a problem with the new schema from metabrainz : 
https://blog.metabrainz.org/2023/05/15/musicbrainz-schema-change-release-2023-05-15-with-upgrade-instructions/

SQL updates : 
https://github.com/metabrainz/musicbrainz-server/blob/master/admin/sql/updates/schema-change/28.all.sql
https://github.com/metabrainz/musicbrainz-server/blob/master/admin/sql/updates/schema-change/28.master_and_standalone.sql
https://github.com/metabrainz/musicbrainz-server/blob/master/admin/sql/updates/schema-change/28.master_only.sql

Thank you for your hard work 💪🏻

**Comment by bt0r** [comment]
I saw that you removed mbslave and the global mindset of the project so this issue is not accurate at this time, i close it

**Comment by lalinsky** [comment]
I'll do the update here - https://github.com/acoustid/mbslave

**Comment by lalinsky** [comment]
https://github.com/acoustid/mbslave/pull/1
