### ISSUE TITLE
mbslave installed via pip: ImportError: No module named mbdata.replication

### ISSUE THREAD

**Issue by MayaMate99** [acoustid/mbdata#8]
I installed mbdata via pip exactly how it's described in the instructions. Unfortunately i get an error each time i try to use the mbslave script:

Traceback (most recent call last):
  File "/home/****/.local/bin/mbslave", line 6, in <module>
    from mbdata.replication import main
ImportError: No module named mbdata.replication

There is only the mbslave script in the directory after doing the pip install.
The script works great if i clone the whole git instead.

**Comment by lalinsky** [comment]
That is strange, it works for me. I suspect you have an older version of mbdata installed somewhere.
